### ISSUE TITLE
Support ETCDv3

### ISSUE THREAD

**Issue by hackallcode** [tarantool/go-vshard-router#7]
Tarantool supports ETCDv3, so let's do it here too

**Comment by KaymeKaydex** [comment]
We are likely to abandon the idea of creating a custom provider, as Viper currently handles remote providers without issues. An example of this can be found in [[this pull request](https://github.com/tarantool/go-vshard-router/pull/8)](https://github.com/tarantool/go-vshard-router/pull/8).

The separate provider for v2 was implemented only because Viper does not support etcd v2 out of the box, and it was specifically designed for the Moonlib library.

At this time, there is no need for custom providers. Viper is sufficient for our use case. The only additional feature needed is support for change handling. By adding this functionality for Viper, we will effectively support it for any source that can be read by Viper.

We will document this separately in the documentation.

**Comment by hackallcode** [comment]
So, your example doesn't work with Tarantool 3.2.

I got `Failed to read topology from etcd{error 26 0  Remote Configurations Error: No Files Found}` error when I use prefix of application.

I got `failed to create vshard router: got error from topology provider; cant init topology with err: duplicate instance name: "00000000-0000-0000-0000-000000000000"` when I use prefix of application + `/config/all` suffix
